### ISSUE TITLE
Multiline comment in :global declaration compiles incorrectly

### ISSUE THREAD

**Issue by reintroducing** [madyankin/postcss-modules#136]
Given the following code:

```scss
:global {
  /*
   * Add the correct display in all browsers.
   */
  summary {
    display: list-item;
  }
}
```

Sass compiles this into:
```scss
:global {
  /*
    * Add the correct display in all browsers.
    */
}
:global summary {
  display: list-item;
}
```

postcss + postcss-modules compiles it to:

```scss
{
  /*
    * Add the correct display in all browsers.
    */
}
summary {
  display: list-item;
}
```

**Reproduction here:** https://stackblitz.com/edit/node-2pmbyx?file=sass.js,postcss.js

**Original Vite bug where this was found:** https://github.com/vitejs/vite/issues/8480
